version: "3.9"
services:
  mysql:
    ports:
      - "3306:3306"
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test

  redis:
    ports:
      - "6379:6379"
    image: redis:5
