spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test
  jpa:
    hibernate:
      ddl-auto: update
# ?????????
# app:
#   sms:
#     provider: tencent